language: php

cache:
  directories:
    - ~/.composer/cache

php:
  - 5.5

sudo: false

before_install:
  - phpenv config-add .travis.php.ini

install:
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: 09f42fadc598b61e923c32f5ce03cf22f166bd011c8743b93b6b68e3c919b821 

after_script:
  - ./bin/test-reporter
