language: php

cache:
  directories:
    - ~/.composer/cache

php:
  - 5.6
  - 7.0

sudo: false

before_install:
  - cp .travis.php_$(phpenv version-name).ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: 09f42fadc598b61e923c32f5ce03cf22f166bd011c8743b93b6b68e3c919b821 

after_script:
  - ./bin/test-reporter
